Update: improved docker checks 1

diff --git a/.github/workflows/prestaging.yml b/.github/workflows/prestaging.yml
--- a/.github/workflows/prestaging.yml
+++ b/.github/workflows/prestaging.yml
@@ -115,9 +115,6 @@ jobs:
           echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
           
           cd /home/ubuntu/resumeoptimizer/
-          
-          # # Start Docker service
-          # sudo systemctl start docker
 
           # Pull the latest image
           docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/resumeoptimizer:latest
@@ -135,25 +132,25 @@ jobs:
             echo "Docker Compose already installed."
           fi
           
-          # Run docker commands using Docker Compose plugin syntax
-          run_docker_compose() {
-            if command -v docker-compose &> /dev/null
-            then
-              echo "Using docker-compose"
-              sudo docker-compose down || echo "Docker Compose down failed or not necessary"
-              sudo docker-compose up -d || echo "Docker Compose up failed"
-            elif docker compose version &> /dev/null
-            then
-              echo "Using docker compose"
-              sudo docker compose down || echo "Docker Compose down failed or not necessary"
-              sudo docker compose up -d || echo "Docker Compose up failed"
-            else
-              echo "Neither docker-compose nor docker compose are installed."
-              exit 1
-            fi
-          }
+          # # Run docker commands using Docker Compose plugin syntax
+          # run_docker_compose() {
+          #   if command -v docker-compose &> /dev/null
+          #   then
+          #     echo "Using docker-compose"
+          #     sudo docker-compose down || echo "Docker Compose down failed or not necessary"
+          #     sudo docker-compose up -d || echo "Docker Compose up failed"
+          #   elif docker compose version &> /dev/null
+          #   then
+          #     echo "Using docker compose"
+          #     sudo docker compose down || echo "Docker Compose down failed or not necessary"
+          #     sudo docker compose up -d || echo "Docker Compose up failed"
+          #   else
+          #     echo "Neither docker-compose nor docker compose are installed."
+          #     exit 1
+          #   fi
+          # }
 
-          run_docker_compose
+          # run_docker_compose
     
     - name: Setup crontab for Docker cleanup on the server with logging
       uses: appleboy/ssh-action@master
