Update: improved docker checks

diff --git a/.github/workflows/prestaging.yml b/.github/workflows/prestaging.yml
--- a/.github/workflows/prestaging.yml
+++ b/.github/workflows/prestaging.yml
@@ -136,8 +136,24 @@ jobs:
           fi
           
           # Run docker commands using Docker Compose plugin syntax
-          sudo docker compose down || echo "Docker Compose down failed or not necessary"
-          sudo docker compose up -d || echo "Docker Compose up failed"
+          run_docker_compose() {
+            if command -v docker-compose &> /dev/null
+            then
+              echo "Using docker-compose"
+              sudo docker-compose down || echo "Docker Compose down failed or not necessary"
+              sudo docker-compose up -d || echo "Docker Compose up failed"
+            elif docker compose version &> /dev/null
+            then
+              echo "Using docker compose"
+              sudo docker compose down || echo "Docker Compose down failed or not necessary"
+              sudo docker compose up -d || echo "Docker Compose up failed"
+            else
+              echo "Neither docker-compose nor docker compose are installed."
+              exit 1
+            fi
+          }
+
+          run_docker_compose
     
     - name: Setup crontab for Docker cleanup on the server with logging
       uses: appleboy/ssh-action@master
